project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"
    - "PREVIEW_INSTRUCTIONS.md"
    - "!extras/**"
  resources:
    - CNAME
website:
  title: "nadia"
  navbar:
    background: "#ffffff"
    logo: logo.svg
    left:
      - href: nosotros.qmd
        text: "Nosotros"
      - href: investigacion.qmd
        text: "Investigación"
      - href: red.qmd
        text: "Redes"
      - href: blog.qmd
        text: "Opinión"  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    lang: es



